apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-db-mongo
  name: auth-db-mongo-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32004
  selector:
    app: auth-db-mongo
  type: NodePort
