apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-micro
  name: user-micro-svc
spec:
  ports:
    - port: 6001
      protocol: TCP
      targetPort: user-port
      nodePort: 32003
  selector:
    app: user-micro
  type: NodePort
