apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-db-mongo-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
  storageClassName: mongo-sc
