apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-micro
  name: chat-micro-svc
spec:
  ports:
    - port: 6000
      protocol: TCP
      targetPort: chat-port
      nodePort: 32001
  selector:
    app: chat-micro
  type: NodePort
