apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-micro-deployment
  labels:
    microservice: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-micro
  template:
    metadata:
      name: auth-micro-pod
      labels:
        app: auth-micro
    spec:
      containers:
        - name: auth-micro
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-micro-configmap
                  key: port
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db-mongo-secrets
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-mongo-secrets
                  key: password
            - name: MONGODB_CONNECTION_STRING
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@auth-db-mongo-svc:27017"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-db-mongo-secrets
                  key: jwt_secret
          image: leballote/auth_service

          # command: ["tail", "-f", "/dev/null"]
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "1"
          #   requests:
          #     memory: 256Mi
          #     cpu: "0.2"
          ports:
            - containerPort: 6002
              name: auth-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: auth-port
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: auth-port
            failureThreshold: 30
            periodSeconds: 10
