apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db-mongo
  name: user-db-mongo-svc
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32002
  selector:
    app: user-db-mongo
  type: NodePort
