apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphql-gateway
  name: graphql-gateway-svc
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: graphql-port
      nodePort: 32100
  selector:
    app: graphql-gateway
  type: NodePort
