apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front-svc
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: https
      nodePort: 32200
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
      nodePort: 32201
  selector:
    app: front
  type: LoadBalancer
